name: CI
on:
  pull_request:
    branches:
      - master
      - 'release-'
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
      - 'at/test-ci-reusable'
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  

jobs:
  tests:
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        group:
          - InterfaceI
          - InterfaceII
          - Extensions
          - Downstream
          - RegressionI
    uses: "SciML/.github/.github/workflows/tests.yml@master"
    with:
      concurrent-jobs: true 
      group: ${{ matrix.group }}
    secrets: "inherit"
