name: IntegrationTest
on:
  push:
    branches:
      - master
      # - at/test-ci-reusable
    tags:
      - v*
  pull_request:
    paths-ignore:
        - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch || github.ref != 'v*' }}

jobs:
  test:
    name: "${{ matrix.package.repo }}"
    strategy:
      fail-fast: false
      matrix:
        package:
          - {owner: SciML, repo: SciMLBase.jl, group: Downstream}
          - {owner: SciML, repo: Catalyst.jl, group: All}
          - {owner: SciML, repo: CellMLToolkit.jl, group: All}
          - {owner: SciML, repo: DataDrivenDiffEq.jl, group: Downstream}
          - {owner: SciML, repo: SBMLToolkit.jl, group: All}
          - {owner: SciML, repo: StructuralIdentifiability.jl, group: All}
          - {owner: SciML, repo: ModelingToolkitStandardLibrary.jl}
          - {owner: SciML, repo: ModelOrderReduction.jl, group: All}
          - {owner: SciML, repo: MethodOfLines.jl, group: 2D_Diffusion}
          - {owner: SciML, repo: MethodOfLines.jl, group: DAE}
          - {owner: SciML, repo: MethodOfLines.jl, group: Interface}
          - {owner: SciML, repo: NeuralPDE.jl, group: NNPDE}
          - {owner: ai4energy, repo: Ai4EComponentLib.jl, group: Downstream}
    uses: "SciML/.github/.github/workflows/downstream.yml@test"
    with:
      owner: ${{ matrix.package.owner }}
      repo: ${{ matrix.package.repo }}
      group: ${{ matrix.package.group }}
    secrets: "inherit"
